### ISSUE TITLE
rename this repo

### ISSUE THREAD

**Issue by attila-lendvai** [ethersphere/bee-docs#109]
the name of this repo is very confusing.

i propose, in this order: `bee-manual` or `bee-manual-website`, or maybe `docs.ethswarm.org` where it is available online.

`bee-documentation` would suggest that it also contains internal, codebase related stuff, implementation decisions, coding guidelines, etc.

if it's decided and becomes actionable, then i'm willing to look into the details of the process. IIRC github will keep redirects that keep even fetching and pushing functional using the old repo urls, and redirects the web browser upon visiting the old url.

**Comment by significance** [comment]
@attila-lendvai afaik the repo is named this way to satisfy github pages. 

it would be amazing if you are able to look into the details of the process of improving the repo name, we have a similar situation for other sites we're using github pages to host for w2. thanks!

cc: @vandot

**Comment by vandot** [comment]
@attila-lendvai as @significance said this unfortunate name is due to hosting docs on github pages check [section 3](https://docs.github.com/en/github/working-with-github-pages/creating-a-github-pages-site)

**Comment by attila-lendvai** [comment]
i don't think the repo name is relevant when it is installed on a custom domain. but i didn't know anything about gh-pages about an hour ago, so take this with a piece of salt.

consider that `docs.github.io` has nothing to do with either ethersphere, or docs.ethswarm.org.

after an hour of furious clicking and reading around, i have managed to publish the bee docs on my domain: http://bee.lendvai.name/

- cloned the docs.github.io repo into my github account
- enabled github-pages in the repo settings
- set branch to "gh-pages"
- changed the "custom domain" in the repo settings, which seems to add a commit into the `gh-pages` branch that changes the CNAME file in the repo's toplevel. i have verified this by deleting this commit, force pushing, and then re-adding it by hand and pushing it.
- added a (CNAME www attila-lendvai.github.io) to my DNS

### conclusion

with weak confidence: the repo can probably be renamed to anything, and stuff will keep on working.

**Comment by attila-lendvai** [comment]
if you attempt a repo rename, then don't forget to grep the entire repo contents for the old repo name! some files are referring to it...

**Comment by significance** [comment]
@attila-lendvai nice work! thanks for this!

**Comment by vojtechsimetka** [comment]
sounds like this can be closed
