### ISSUE TITLE
Use latest version in docs

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee-docs#118]
## Story
As a consumer of the bee documentation, I want that it always instructs me to download the latest version of anything I am instructed to install, such that I don't accidentally run obsolete software

## Background
This issue was made after  finding out that the user is instructed to install bee-clef v4.1 in our docs, whereas bee-clef is already at v4.4. We need to inspect our docs, see where else there is a possibility of referring obsolete software and make the precautions to ensure that this won't happen again in the future.

## Acceptance criteria
- All software that is referenced in our docs is up-to-date
- Improvements were made in order to ensure that we minimize the chances to refer obsolete software in the future

**Comment by crtahlin** [comment]
Use the "latest" tag for the last version in git?

**Comment by Eknir** [comment]
Yup, that's what we spoke about with @vandot and @sig before

**Comment by significance** [comment]
@Eknir @crtahlin did you some quick tests and as far as i can see the `latest` tag works for Docker only at the moment, and this is currently using `beta` in place of `latest`? perhaps something we can add soon, but i have manually updated version numbers now for now.

**Comment by vandot** [comment]
At some moment it can happen that latest is latest stable, but beta is always latest stable, until we reach 1.0, we can set auto update of docs if needed? (well because we migrated to bee we will have to wait for feeds support, version bump inside docs can be automated)

**Comment by Eknir** [comment]
@vandot @significance , is this issue completed? I know that now, the docs refer to the correct release, but what steps are taken to ensure that it will always point to the correct release?

**Comment by significance** [comment]
@Eknir this one is a bit tricky because there are loads of places where the version number is used. eg. all the different packages we ask the user to `wget` and so on. Search in the docs proj for the current version number (without the v) to see.

Part of me also thinks this may end up leading to confusion and we are better off with specific version numbers but i could be convinced 😅 

I know we also discussed in #documentation thread - can't remember where we left it. @vandot perhaps you could advise on the level of effort involved here to change everything over.

Of course, unless we change everything then the find and replace will still need to be a part of the docs new release cycle.

**Comment by vandot** [comment]
@Eknir @significance for docker we can advise users to use specific tag e.g. `beta` but for packages not, what I often find in OSS projects is `<versions>` and explanation to go to releases page and take version whatever you want. Better to have one additional step rather then have wrong package version in the docs. Something like this:
```
wget https://github.com/ethersphere/bee/releases/download/v<version>/bee_<version>_amd64.deb -O bee.deb
sudo dpkg -i bee.deb
```

**Comment by Eknir** [comment]
@vandot , good suggestion. @significance , wdyt?

**Comment by significance** [comment]
the beta bit is already in the docker docs, tbh i had forgotten about the conversation, thanks @vandot for the reminder 🙌 

changing the version bit, i am comfortable doing this manually for now so we can retain the frictionless onboard, there are already other manual processes that need to be take care of. i will add a checklist for this so it doesn't get forgotten.
