### ISSUE TITLE
challenges with ENS resolver instructions

### ISSUE THREAD

**Issue by jpritikin** [ethersphere/bee-docs#135]
It took me a while to guess the correct syntax for the bee.yaml file,

```
resolver-options: [ "https://cloudflare-eth.com" ]
```

Seems to need the square brackets? Anyway, it would also be nice if the doc recommended a test request such as,

```
http://localhost:1633/bzz/swarm.eth/
```

**Comment by jpritikin** [comment]
This issue is regarding https://docs.ethswarm.org/docs/getting-started/host-your-website-using-ens

**Comment by significance** [comment]
thanks for you feedback @jpritikin i'll feed this in
