### ISSUE TITLE
Update configuration default values

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee-docs#138]
The page https://docs.ethswarm.org/docs/installation/configuration (chapter `configuration options`) shows certain default values (`payment threshold`, `payment tolerance`, `swap-initial-deposit`) which are outdated. 
The task is to go over all configuration options and bring it up-to-date with the most recent default values. Note. It may also be the case that some configuration options are missing and others are deprecated.
You can learn about the default configuration of a bee node by calling `bee printconfig`

**Comment by significance** [comment]
thanks @Eknir
