### ISSUE TITLE
Document gateway-mode

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee-docs#163]
Bee exposes the possibility to start the node in a "gateway-mode", but this functionality is nowhere described in our docs, nor API documentation. 

We should have a section in our docs on this "gateway-mode" and somehow reflect this gateway mode in our API documentation. 

Suggestions on how to reflect it in API docs:

- add warnings to all endpoints that are changed in the gateway-mode
- create a copy of the API docs, defining how the API looks in gateway-mode.
- open for other suggestions

**Comment by Eknir** [comment]
@janos , could you please leave a comment here about the design principle, underlying the gateway mode?

**Comment by janos** [comment]
The gateway mode is a consequence of adding endpoints to the exposed API which make permanent changes to one node's state, such pinning, or requires signing as pss. Gateway mode is a way to protect the node from misuse of its API when it is exposed publicly. This protection could be achieved also by proxy configuration, but it was found more user friendly to just have the option inside the node.

My opinion is that gateways are just a helper tools to gain adoption with convenience. Gateways are centralized and closed by the provider and cannot be trusted which is agains the purpose of the swarm.

Ideally, the gateway mode should not be needed. All state changing endpoints should be in the debug api. Pinning and tagging management endpoints were part of the debug api initially, but moved later to the main api.

Gateway mode disables completely endpoints:

- /pss
- /pin
- /tags

This is not documented in the API spec, but the API response will be with the Forbidden 403 status code.

Gateway mode also protects pinning, encryption and tagging on upload endpoints (by disabling headers), but does not disable the upload endpoints. API spec lists 403 responses which would be returned in that case. Maybe it should be improved with a description on that response in the spec.

**Comment by significance** [comment]
this is perfect, thanks @janos @Eknir - i will add this in the next round
