### ISSUE TITLE
Upgrading information refers to missing instructions

### ISSUE THREAD

**Issue by mfw78** [ethersphere/bee-docs#179]
In the Ubuntu / Debian / Raspbian section, it refers to "the instructions above" for downloading / installing. There are no instructions on that page with reference to downloading / installing. Suggest a hyperlink in place to the instructions, or a snippet insert.

**Comment by ldeffenb** [comment]
There's an infinite reader-redirection loop in the upgrade instructions:

Automatic Migration Procedure says:
Upgrade your node, as you normally would (see below).

Manual Migration Procedure also says:
Upgrade your node, as you normally would (see below).

Upgrade Procedure says:
Now follow the steps above to download the new package and install the new version, as usual.

But nowhere does it describe how to "download the new package" or the command to initiate the installation.
