### ISSUE TITLE
download file example url error

### ISSUE THREAD

**Issue by 1057437122** [ethersphere/bee-docs#193]
the correct url should ends with a `/`, like `curl -OJ http://localhost:1633/bzz/042d4fe94b946e2cb51196a8c136b8cc335156525bf1ad7e86356c2402291dd4/`, the document doesn't tell us, this doc-error will waste a lot of ours and supporter-team's time

**Comment by attila-lendvai** [comment]
thanks for the report! this has been fixed meanwhile.
