### ISSUE TITLE
configuration is discussed at two places

### ISSUE THREAD

**Issue by attila-lendvai** [ethersphere/bee-docs#220]
there are two places that get into the details of the configuration:

1. https://docs.ethswarm.org/docs/installation/install
2. https://docs.ethswarm.org/docs/working-with-bee/configuration

i think the first one should be deleted, and replaced by a note that points to the second one.

@significance, advice is needed on how to proceed (or from anyone else who has a vision for the documentation. @Eknir maybe?)

**Comment by significance** [comment]
thanks for this dude, i think we need to review the onboarding procedure, the configuration discussion in the install page is in response to the sheer amount of configuration changes needed to have a basic functioning node, this should not really be required, but at the moment, it is.
