### ISSUE TITLE
Refactor "bee start" and "systemctl start bee"

### ISSUE THREAD

**Issue by mfw78** [ethersphere/bee-docs#232]
From experience in the discord support channel, it seems to be a very consistent issue where people are having conflicting configurations / bee data directories, associated with a misunderstanding surrounding `bee start` and `systemctl start bee`.

Therefore, I would suggest a very strict opinion in the docs, whereby all methods for running bee should use `systemctl start bee`, or `docker-compose up -D` as the documented method may cover.

I would then suggest an "Advanced" section dedicated to packagers / Dockerfile creators/maintainers covering the running of `bee start`.

**Comment by significance** [comment]
good feedback, thanks for this @mfw78
