### ISSUE TITLE
Possible missing command for retrieving wallet password

### ISSUE THREAD

**Issue by Barryt06** [ethersphere/bee-docs#262]
Hi, 

I am not sure if this is an issue or if I did something wrong. 

While following the instructions here, https://docs.ethswarm.org/docs/installation/fund-your-node#with-bee-clef, I ran into an issue importing my wallet into Metamask. 

What I did: 

`sudo ls /var/lib/bee-clef/keystore`
`sudo cat /var/lib/bee-clef/keystore/UTC...`
Saved it as a json file. 
Copied the password outputed from `sudo cat /var/lib/bee-clef/password`
Went to MM and imported as JSON file, selected my json file and entered the passphrase.

Result: 
The password did not work for me and I received an error in Metamask "Key derivation failed - possibly wrong passphrase"

How I got it to work:

`sudo ls /var/lib/bee-clef/passwords`
It lists a directory _bee-0__[my wallet address]
`sudo cat /var/lib/bee-clef/passwords/bee-0_[my wallet address]`

The password return from the last command above worked with my json file.

**Comment by NoahMaizels** [comment]
Instructions added here:

https://docs.ethswarm.org/docs/bee/working-with-bee/backups
