### ISSUE TITLE
Should contain the formula how the total amount of BZZ that will be paid is calculated

### ISSUE THREAD

**Issue by vporton** [ethersphere/bee-docs#281]
https://docs.ethswarm.org/docs/access-the-swarm/keep-your-data-alive/:

> The total amount of BZZ that will be paid for the batch is calulated from this figure and the batch depth.

The documentation should contain the formula how this is calculated or at least a general idea of it.

BTW, "calculated" is misspelled.

**Comment by agazso** [comment]
Good point!

For the record the formula is `priceInBZZ = amount * (2^depth) * 1e-16` , where `amount` and `depth` are parameters of the postage stamp.

**Comment by vporton** [comment]
> when your chunks will run out of balance ... can be estimated based on the current price and the remaining batch balance.

How exactly to estimate this also should be documented.
