### ISSUE TITLE
unclear instructions, external SSD dependency not mentionned

### ISSUE THREAD

**Issue by tamas6** [ethersphere/bee-docs#295]
https://docs.ethswarm.org/docs/installation/install/

###  this part is a bit problematic:
`sudo vi /etc/bee/bee.yaml`
`sudo systemctl restart bee`
I know `vi` is still a thing but `nano` is more preferable (personal taste, yes👌)
If you are at this point of the install and strictly follow docs you didn't even start bee yet ( `restart bee` was unaffective ).

### +
if you `sudo nano /etc/bee/bee.yaml` it's better if we imply to delete all the ##commented lines and only keep the modifieds
I recommend to suggest using a [yaml formatter](http://www.yamllint.com/) to check if the remaining code is applicable.

### +
rumbling through the Raspbian installation one would benefit of mentioning external SSD usage for bee dist

**Comment by GasperX93** [comment]
Raspberry Pi is no longer covered in the Documentation
