### ISSUE TITLE
nonexist source for armv7 version 

### ISSUE THREAD

**Issue by tamas6** [ethersphere/bee-docs#298]
### https://docs.ethswarm.org/docs/installation/install/
`wget https://github.com/ethersphere/bee/releases/download/v1.7.0/bee_1.7.0_armv7.deb`
`sudo dpkg -i bee_1.7.0_armv7.deb`

i think

**Comment by kristianpaul** [comment]
Yeah In https://docs.ethswarm.org/docs/installation/install   bee_1.8.1_armv7.deb looks like need to be fixed to be bee_1.8.1_armvhf.deb also a similar situation for clef there https://docs.ethswarm.org/docs/installation/rasp-bee-ry-pi/
