### ISSUE TITLE
Configuration Example Confusion

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee-docs#299]
The configuration example at https://docs.ethswarm.org/docs/working-with-bee/configuration/#configuration-file shows mainnet: true and network-id: "10".  One or the other should be changed to match.

**Comment by ef3n9r98** [comment]
Hi @agazso, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!
