### ISSUE TITLE
missing: a description of what exactly a postage stamp "dilution" is 

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee-docs#399]
https://docs.ethswarm.org/api/#tag/Postage-Stamps/paths/~1stamps~1dilute~1%7Bbatch_id%7D~1%7Bdepth%7D/patch

The dilute `endpoint` doesnt actually describe what dilution, why it is needed or what the consequences of dilution are:
- increase data uploads?
- lowered TTLs?

**Comment by NoahMaizels** [comment]
See https://github.com/ethersphere/bee-docs/pull/456
