### ISSUE TITLE
missing information on salud health service

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee-docs#404]
Would be great to include information about the salud health service in the "monitoring your node" section

https://docs.ethswarm.org/docs/working-with-bee/monitoring

**Comment by NoahMaizels** [comment]
I think salud is not intended for diagnosing issues for end users and is rather used for Docker / Kubernetes health checks. I have explained this and also other more useful status related endpoints here: https://docs.ethswarm.org/docs/bee/working-with-bee/troubleshooting#guide-to-status-related-endpoints
