### ISSUE TITLE
different output from what is specified in the docs during bee install 

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee-docs#476]
What i got upon fresh install after uninstalling previous installations described here - (fresh install after uninstalled previous installations based on the docs https://docs.ethswarm.org/docs/bee/working-with-bee/uninstalling-bee#uninstalling-bee):

![image](https://github.com/ethersphere/bee-docs/assets/520570/f0707435-3d8d-4676-a60e-ef21110d9a5a)

What was expected:
![image](https://github.com/ethersphere/bee-docs/assets/520570/7c0568e0-0c0b-4608-bac7-8764d9daac3e)

**Comment by NoahMaizels** [comment]
I believe this is due to incompletely uninstalled previous installation. Try running `sudo apt-get purge bee` (of course after backing up), and installing again
