### ISSUE TITLE
add double quotes `"` around target-neighborhood value to corelate with printconfig output

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee-docs#523]
Docs: https://docs.ethswarm.org/docs/bee/installation/install#set-target-neighborhood-optional

![image](https://github.com/ethersphere/bee-docs/assets/520570/95dfb69f-ea08-46cf-bd60-e9bf09cf5160)
![image](https://github.com/ethersphere/bee-docs/assets/520570/627528b0-54b8-4842-9694-a9524c7aad23)

**Comment by NoahMaizels** [comment]
Done
