### ISSUE TITLE
Document preplay video

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee-docs#69]
Preplay video in browser, instead of downloading.

See: https://gateway.staging.ethswarm.org/files/f8a17811e72578e7b94758ba5cac37bd70278e71cf02866faf2d4dcc433272d9
```
curl -v -H "Content-Type: video/mp4" --data-binary @bbb_sunflower_1080p_30fps_normal.mp4 "https://gateway.staging.ethswarm.org/files?name=bbb_sunflower_1080p_30fps_normal.mp4
https://gateway.staging.ethswarm.org/files/f8a17811e72578e7b94758ba5cac37bd70278e71cf02866faf2d4dcc433272d9
```

**Comment by Eknir** [comment]
@significance , I suggest we put this under an info header in the upload/download tutorial. For video content, it is important to set the Content-Type header. If not set, it won't allow to preplay.

**Comment by significance** [comment]
sorry @Eknir but confused - is this is done automatically in the browser? i guess it is not needed for curl because that does not pre-play? lmk if action required!

**Comment by Eknir** [comment]
This is more about documenting the correct use of content type header

**Comment by significance** [comment]
got it 👍
